export const expenseOptions = [
  { label: "ATM", category: "Cash Withdrawal" },
  { label: "Cash Gift", category: "Cash Gift" },
  { label: "Bank charges", category: "Charges" },
  { label: "Tailoring", category: "Clothing" },
  { label: "Cloth Shopping", category: "Clothing" },
  { label: "Laundry", category: "Clothing" },
  { label: "Footwear", category: "Footwear" },
  { label: "Train Pass", category: "Commute" },
  { label: "Petrol", category: "Commute" },
  { label: "Toll", category: "Commute" },
  { label: "Parking", category: "Commute" },
  { label: "Air", category: "Commute" },
  { label: "Wheel Balancing", category: "Commute" },
  { label: "Wheel Alignment", category: "Commute" },
  { label: "Vehicle Care", category: "Vehicle Care" },
  { label: "Vehicle Repair", category: "Vehicle Repair" },
  { label: "Cinema", category: "Entertainment" },
  { label: "Activity", category: "Entertainment" },
  { label: "Gym", category: "Fitness" },
  { label: "Yoga", category: "Fitness" },
  { label: "Grocery", category: "Food and Grocery" },
  { label: "Supermarket", category: "Food and Grocery" },
  { label: "BigBasket", category: "Food and Grocery" },
  { label: "Milk", category: "Food and Grocery" },
  { label: "Fruits and Vegetables", category: "Food and Grocery" },
  { label: "Fruits", category: "Food and Grocery" },
  { label: "Restaurant", category: "Food and Grocery" },
  { label: "Vegetables", category: "Food and Grocery" },
  { label: "Coffee", category: "Food and Grocery" },
  { label: "Dosa Batter", category: "Food and Grocery" },
  { label: "Curd", category: "Food and Grocery" },
  { label: "Flour shop", category: "Food and Grocery" },
  { label: "Electricals", category: "Furnishing" },
  { label: "Gadgets", category: "Gadgets" },
  { label: "Mobile", category: "Gadgets" },
  { label: "Headset", category: "Gadgets" },
  { label: "Accessories", category: "Gadgets" },
  { label: "Gift", category: "Gift" },
  { label: "Hair cut", category: "Grooming" },
  { label: "Grooming", category: "Grooming" },
  { label: "Household", category: "Household" },
  { label: "Insurance", category: "Insurance" },
  { label: "Vehicle Insurance", category: "Insurance" },
  { label: "Gadgets Insurance", category: "Insurance" },
  { label: "Mutual fund", category: "Investments" },
  { label: "Share market", category: "Investments" },
  { label: "Gold", category: "Investments" },
  { label: "Silver", category: "Investments" },
  { label: "Medical", category: "Medical" },
  { label: "Misc", category: "Misc" },
  { label: "Internet", category: "Mobile & Internet" },
  { label: "Mobile Recharge", category: "Mobile & Internet" },
  { label: "AI", category: "Mobile & Internet" },
  { label: "Tour", category: "Tour" },
  { label: "Tour Food", category: "Tour" },
  { label: "Tour Petrol", category: "Tour" },
  { label: "Tour Room", category: "Tour" },
  { label: "Tour Toll", category: "Tour" },
  { label: "Tour Donation", category: "Tour" },
  { label: "Trip", category: "Travel" },
  { label: "Cab", category: "Travel" },
  { label: "Auto", category: "Travel" },
  { label: "Emergency", category: "Unexpected" },
  { label: "Unexpected", category: "Unexpected" },
  { label: "Gas", category: "Utility Bills" },
  { label: "Lab test", category: "Hospital" },
  { label: "Hospital", category: "Hospital" },
  { label: "Property Tax", category: "Tax" },
  { label: "Water Tax", category: "Tax" },
  { label: "EB", category: "Utility Bills" },
  { label: "Books", category: "Books" },
  { label: "Coworking space", category: "Reading" },
  { label: "Google Play", category: "Utility Bills" },
  { label: "Stationery", category: "Stationery" },
  { label: "Xerox", category: "Stationery" },
  { label: "Toys", category: "Toys" },
  { label: "Unknown", category: "Unknown" },
  { label: "Donation", category: "Donation" },
  { label: "Loan given", category: "Loan given" },
  { label: "Dishwasher Salt", category: "Dishwasher" },
  { label: "Dishwasher Detergent", category: "Dishwasher" },
  { label: "Dishwasher Rinseaid", category: "Dishwasher" },
  { label: "Dishwasher Combo", category: "Dishwasher" },
  { label: "Pooja Items", category: "Pooja Items" },
  { label: "Personal care", category: "Personal Care" },
  { label: "School fees", category: "School fees" },
  { label: "School misc", category: "School fees" },
  { label: "Dance School", category: "Dance School" },
];

export const paymentMethods = [
  // Amazon Pay
  { label: "Amazon Pay", category: "Amazon Pay" },

  // Google Pay
  { label: "Google Pay", category: "Google Pay" },

  // Cash
  { label: "Cash", category: "Cash" },

  // Others
  { label: "Pluxee", category: "Others" },
  { label: "Fastag", category: "Others" },
  { label: "Netbanking", category: "Others" },
  { label: "Card", category: "Others" },
  { label: "Bank app", category: "Others" },
];