export const expenseOptions = [
  { label: "ATM", category: "Cash Withdrawal" },
  { label: "Cash Gift", category: "Cash Gift" },
  { label: "Bank charges", category: "Charges" },
  { label: "Tailoring", category: "Clothing" },
  { label: "Cloth Shopping", category: "Clothing" },
  { label: "Laundry", category: "Clothing" },
  { label: "Footwear", category: "Footwear" },
  { label: "Train Pass", category: "Commute" },
  { label: "Petrol", category: "Commute" },
  { label: "Toll", category: "Commute" },
  { label: "Parking", category: "Commute" },
  { label: "Air", category: "Commute" },
  { label: "Wheel Balancing", category: "Commute" },
  { label: "Wheel Alignment", category: "Commute" },
  { label: "Vehicle Care", category: "Vehicle Care" },
  { label: "Vehicle Repair", category: "Vehicle Repair" },
  { label: "Cinema", category: "Entertainment" },
  { label: "Activity", category: "Entertainment" },
  { label: "Gym", category: "Fitness" },
  { label: "Yoga", category: "Fitness" },
  { label: "Grocery", category: "Food and Grocery" },
  { label: "Supermarket", category: "Food and Grocery" },
  { label: "BigBasket", category: "Food and Grocery" },
  { label: "Milk", category: "Food and Grocery" },
  { label: "Fruits and Vegetables", category: "Food and Grocery" },
  { label: "Fruits", category: "Food and Grocery" },
  { label: "Restaurant", category: "Food and Grocery" },
  { label: "Vegetables", category: "Food and Grocery" },
  { label: "Coffee", category: "Food and Grocery" },
  { label: "Dosa Batter", category: "Food and Grocery" },
  { label: "Curd", category: "Food and Grocery" },
  { label: "Flour shop", category: "Food and Grocery" },
  { label: "Electricals", category: "Furnishing" },
  { label: "Gadgets", category: "Gadgets" },
  { label: "Mobile", category: "Gadgets" },
  { label: "Headset", category: "Gadgets" },
  { label: "Accessories", category: "Gadgets" },
  { label: "Gift", category: "Gift" },
  { label: "SGB", category: "Gold" },
  { label: "GoldBees", category: "Gold" },
  { label: "Hair cut", category: "Grooming" },
  { label: "Grooming", category: "Grooming" },
  { label: "Household", category: "Household" },
  { label: "Insurance", category: "Insurance" },
  { label: "Vehicle Insurance", category: "Insurance" },
  { label: "Gadgets Insurance", category: "Insurance" },
  { label: "Mutual Funds Wife", category: "Investments" },
  { label: "Mutual Funds Husband", category: "Investments" },
  { label: "Kite Wife", category: "Investments" },
  { label: "Kite Husband", category: "Investments" },
  { label: "Coin Husband", category: "Investments" },
  { label: "Coin Wife", category: "Investments" },
  { label: "Icici Direct", category: "Investments" },
  { label: "Daughter SSA", category: "Investments" },
  { label: "Gold", category: "Investments" },
  { label: "Silver", category: "Investments" },
  { label: "Nattu Marundhu", category: "Medical" },
  { label: "Medical", category: "Medical" },
  { label: "Misc", category: "Misc" },
  { label: "Internet", category: "Mobile & Internet" },
  { label: "BSNL Husband", category: "Mobile & Internet" },
  { label: "Airtel Husband", category: "Mobile & Internet" },
  { label: "Airtel Father", category: "Mobile & Internet" },
  { label: "BSNL Daughter", category: "Mobile & Internet" },
  { label: "Jio Wife", category: "Mobile & Internet" },
  { label: "Airtel Wife", category: "Mobile & Internet" },
  { label: "Airtel Mother", category: "Mobile & Internet" },
  { label: "AI", category: "Mobile & Internet" },
  { label: "Tour", category: "Tour" },
  { label: "Tour Food", category: "Tour" },
  { label: "Tour Petrol", category: "Tour" },
  { label: "Tour Room", category: "Tour" },
  { label: "Tour Toll", category: "Tour" },
  { label: "Tour Donation", category: "Tour" },
  { label: "Trip", category: "Travel" },
  { label: "Cab", category: "Travel" },
  { label: "Auto", category: "Travel" },
  { label: "Emergency", category: "Unexpected" },
  { label: "Unexpected", category: "Unexpected" },
  { label: "Gas", category: "Utility Bills" },
  { label: "Lab test", category: "Hospital" },
  { label: "Hospital", category: "Hospital" },
  { label: "Property Tax", category: "Tax" },
  { label: "Water Tax", category: "Tax" },
  { label: "EB", category: "Utility Bills" },
  { label: "Books", category: "Books" },
  { label: "Coworking space", category: "Reading" },
  { label: "Google Play", category: "Utility Bills" },
  { label: "Stationery", category: "Stationery" },
  { label: "Xerox", category: "Stationery" },
  { label: "Toys", category: "Toys" },
  { label: "Sevoor athai death", category: "Sevoor athai death" },
  { label: "Unknown", category: "Unknown" },
  { label: "Donation", category: "Donation" },
  { label: "Susila Patti", category: "Hospital" },
  { label: "Loan given", category: "Loan given" },
  { label: "Dishwasher Salt", category: "Dishwasher" },
  { label: "Dishwasher Detergent", category: "Dishwasher" },
  { label: "Dishwasher Rinseaid", category: "Dishwasher" },
  { label: "Dishwasher Combo", category: "Dishwasher" },
  { label: "Pooja Items", category: "Pooja Items" },
  { label: "Chennai Pooja Mar 2025", category: "Pooja Items" },
  { label: "Personal care Wife", category: "Personal Care" },
  { label: "Personal care Husband", category: "Personal Care" },
  { label: "Personal care Daughter", category: "Personal Care" },
  { label: "School fees", category: "School fees" },
  { label: "School misc", category: "School fees" },
  { label: "Dance School", category: "Dance School" },
];

export const paymentMethods = [
  // Amazon Pay
  { label: "Apay Wife", category: "Amazon Pay" },
  { label: "Apay Husband", category: "Amazon Pay" },

  // Google Pay
  { label: "Gpay Husband", category: "Google Pay" },
  { label: "Gpay Wife", category: "Google Pay" },

  // Cash
  { label: "Cash Husband", category: "Cash" },
  { label: "Cash Wife", category: "Cash" },

  // Others
  { label: "Pluxee", category: "Others" },
  { label: "Fastag", category: "Others" },
  { label: "Netbanking HDFC", category: "Others" },
  { label: "Card Husband", category: "Others" },
  { label: "SimplePay Husband", category: "Others" },
  { label: "Payzapp Husband", category: "Others" },
  { label: "Samsung Pay Husband", category: "Others" },
  { label: "Hdfc bank app", category: "Others" },
];

const aaa = [{comment: "", date: "01/11/1111", expenseAmount: "1", expenseCategory: "Books", id: "1759502745843", paymentCategory: "Apay Husband"}, {comment: "aa", date: "01/11/1111", expenseAmount: "2", expenseCategory: "Books", id: "1759502745844", paymentCategory: "Apay Husband"}, {comment: "", date: "01/11/1111", expenseAmount: "3", expenseCategory: "Car", id: "1759502745845", paymentCategory: "Apay Wife"}];
